steps:

# This script runs both via bash (macOS/Linux) and cmd (Windows).
# Keep it both valid bash and batch or break it out conditionally.
- script: |
    echo System Environment
    set
    echo .NET Core Info
    dotnet --info
  displayName: Dump Environment

- task: MSBuild@1
  inputs:
    solution: CoreBuild.proj
    configuration: '$(msbuild.configuration)'
  displayName: Build